### ISSUE TITLE
Doesn't work with dropbear in arch or kali linux

### ISSUE THREAD

**Issue by corbinlc** [connectbot/connectbot#663] opened 2018-11-08 20:20 UTC
UserLAnd sends ssh intents out for people to connect to their boxes which we create.  We direct people to connectbot if they have no SSH app that supports such an intent installed yet.  This has worked fairly well (except #599 and #619), but now we are adding more distributions that you can install in userland which has brought up a new issue.  Both Arch and Kali linux use newer cyphers (I assume that is the issue) which connectbot does not support.  We get the following error
```
Connection Lost
Key exchange was not finished, connection is closed.
Cannot negotiate, proposals do not match.
```
This works fine with JuiceSSH but we want to stick with connectbot since it is FOSS.  
Any thoughts or any known workaround?

**Comment by corbinlc** [comment] 2018-11-08 23:17
I noticed the last apk release was in Feb of 2017.  What is needed for your team to make a new release?  It appears this issue is already solved in your latest code.  I and my team can help if there is something that is needed to push the latest and greatest out to the world (including $ if that somehow factors into it).  We don't want to make a different ssh app our default and we don't want to fork what you are doing, so please respond and tell us your plans.

**Comment by corbinlc** [comment] 2018-11-08 23:34
https://github.com/connectbot/connectbot/releases. Looks like you have marked 1.9.5 as a release very recently, but people are still seeing 1.9.2 in the play store.  Is it going to get pushed to the play store soon?

**Comment by corbinlc** [comment] 2018-11-08 23:46
Ah several of our devices see the new version, 1.9.5, but the device I mainly uses doesn't.  It is an original pixel.  Did you enable a slow rollout of the apk?  I am going to see if I force close the play store or restart if that gets the play store cache to show me the latest and greatest

**Comment by kruton** [comment] 2018-11-09 00:29
I was doing a staged rollout. I've increased the rollout to 100% of devices, so you should see it soon.

**Comment by corbinlc** [comment] 2018-11-09 05:39
Ok.  I have 1.9.5 from the play store now. It actually doesn't fix this issue.  But using the code straight from the master branch does.  Is this expected from the changes you have made recently?

**Comment by kruton** [comment] 2018-11-09 05:44
No, there are not SSH protocol changes since the last release. I've not written any integration tests for dropbear. If you want to try to reproduce it, you could add a [docker profile](https://github.com/connectbot/sshlib/tree/master/sshlib/src/test/resources/openssh-server) and a [test](https://github.com/connectbot/sshlib/blob/master/sshlib/src/test/java/com/trilead/ssh2/OpenSSHCompatibilityTest.java).

**Comment by kruton** [comment] 2018-11-09 09:16
Okay, I just added Dropbear integration tests that seem to show it's okay at least with the latest Dropbear version. connectbot/sshlib@92e5b8520094e7c8997b7c40d995d68d0866b2e6

Could you give me some more information about your Dropbear version?

**Comment by corbinlc** [comment] 2018-11-09 17:45
The problem is different than I thought.  I has to do with persistent app data.  
Here is the full picture...
1) We launch and ssh server on our side.  
   When we do this from a Debian distro, it uses Dropbear v2016.74.
   When we do this from a Kali distro, it uses Dropbear v2018.76
2) Next we fire an URI intent to connectbot, or whoever is listening, to connect to that server.  We currently always use port 2022.

I tried the Debian one first, and it worked.  I then tried the Kali one and it gave the error mentioned.  I thought this was due to the Kali one being newer, but it turns out the issue is that it is simply different.

It turns out that which ever one I try first works (Debian or Kali) but whichever comes second fails.  Another bread crumb is, if I clear all the app's persistent data, which ever one I try next will work.  When I ran from Android Studio, it didn't use the old data, so it looked good at first, but it actually has the same issue.

So the problem appears to be that connectbot is remembering something about what the connection looked like the last time and expecting it to look the same.  Is there a way to not assume this?  As this breaks anyone who updates connectbot.  Or is there a way to not assume this when the connection is coming from a URI intent?  

Is it that the first URI intent is creating a connectbot host, but the subsequent ones are just reusing that one?

Thanks for getting back to me.

**Comment by corbinlc** [comment] 2018-11-09 17:55
If I simply just delete the host manually in connectbot after every connection, the next connection will work.  Can we make it so all URI intents always create a new host or something like that?

**Comment by corbinlc** [comment] 2018-11-09 18:14
Simply making the nickname unique does not solve this, even though that seems to make two separate hosts in connectbot.

**Comment by corbinlc** [comment] 2018-11-09 22:21
In my case, I want it to treat this like a brand new connection from a brand new host.  Maybe an extra could be added to the intent to tell it to treat this in that manner.  I guess a more sophisticated solution would involve checking if it can connect and if it cannot, then it tries to treat it like it might not be the same host.

**Comment by kruton** [comment] 2018-11-09 23:06
Maybe they're presenting different types of keys (e.g., 2016 version using RSA and 2018 using ECDSA). I'll try to get a repro case and a fix.

**Comment by corbinlc** [comment] 2018-11-10 04:52
That would be great.  Tell me if there is anything you need from me or if you want me to try out a potential fix.

**Comment by corbinlc** [comment] 2018-11-13 17:16
Do you want to try this out using UserLAnd?  I can give you an APK that has kali support built in, so you can bounce back and forth between the version in debian and the version in kali.

**Comment by corbinlc** [comment] 2018-11-15 21:35
Kali
![kali-ssh](https://user-images.githubusercontent.com/1421245/48583169-4b15c580-e8db-11e8-830e-10da2a410111.png)
Debian
![debian-ssh](https://user-images.githubusercontent.com/1421245/48583172-4cdf8900-e8db-11e8-93cc-adf694898b55.png)
Notice the difference in the key exchange algo

**Comment by corbinlc** [comment] 2018-11-15 21:42
I know this is not a permanent solution, but if I blow away the previous host everytime like this...
```
	public TerminalBridge openConnection(Uri uri) throws Exception {
		HostBean host = TransportFactory.findHost(hostdb, uri);

		if (host != null)
			hostdb.deleteHost(host);

		host = TransportFactory.getTransport(uri.getScheme()).createHost(uri);

		return openConnection(host);
	}
```
it works

**Comment by corbinlc** [comment] 2018-11-15 21:44
If there is a simple way to add an intent extra to blow away any conflicting host, but probably above this place it the code, that would work well for our situation.

**Comment by corbinlc** [comment] 2018-11-22 07:01
@kruton  anything I can do to help?

**Comment by projectextremum** [comment] 2018-11-25 06:11
@corbinlc As a side note please do not provide Kali Linux in UserLAnd. I can grasp you are doing it for popularity. But providing easier way to install Kali Linux benefits script kiddies rather than real penetration testers.

**Comment by corbinlc** [comment] 2018-11-26 20:48
@projectextremum we are going to do it simply because our users have asked for it.  We take no stand for or against what users do with our work.  We will add Arch Linux and others for the exact same reason.  I understand your concern though, but that is a rabbit hole we are not going down.

**Comment by kruton** [comment] 2018-11-27 00:34
I haven't had time to look at this further. I initially suspected that it might be EC vs. RSA polluting the KnownHosts, but the screenshots you submitted above seem to indicate they're both using EC. Do they happen to use different size EC keys perhaps?

**Comment by projectextremum** [comment] 2018-11-27 13:41
@corbinlc besides ethical concerns regarding non techie users who get affected by script kiddies, it is a real concern for practical issues regarding project management. I am sure those who ask for Kali Linux in UserLAnd are 11-year olds at best. Real pentester doesn't actually need that, or knows how to set it up in `proot` / `chroot` by himself. So those who ask for Kali linux are just there to disturb you with n00bish issues. Do not take the burden of maintaining the rootfs distribution in UserLAnd. Next probably arises the issue of random clickbait tutorials causing errors for newbies who threaten existence of gitter / irc channels. Clickbait tutorials were criticized on termux gitter for being misleading & incomplete, and next might be your app.

Adding Arch is justified but the user is expected to learn how to set it up in proot :P. But honestly Kali Linux or any other penetration testing distro wasn't needed. I am sure those users hardly convert into useful contributions or issue tracker entries.

Bit out of topic but you ought to think about.

**Comment by corbinlc** [comment] 2018-11-27 22:58
@kruton I will check and get back to you.  I actually made it so Kali can only be launched into VNC (no SSH) until we solve this issue.  I will back out that change locally and look at the keys generated.

**Comment by corbinlc** [comment] 2018-11-28 00:38
kali keys (I added the .txt suffix to make github happy)



[dropbear_rsa_host_key.txt](https://github.com/connectbot/connectbot/files/2622374/dropbear_rsa_host_key.txt)
[dropbear_ecdsa_host_key.txt](https://github.com/connectbot/connectbot/files/2622375/dropbear_ecdsa_host_key.txt)
[dropbear_dss_host_key.txt](https://github.com/connectbot/connectbot/files/2622376/dropbear_dss_host_key.txt)

**Comment by corbinlc** [comment] 2018-11-28 00:39
debian keys (I added the .txt suffix to make github happy)

[dropbear_rsa_host_key.txt](https://github.com/connectbot/connectbot/files/2622378/dropbear_rsa_host_key.txt)
[dropbear_ecdsa_host_key.txt](https://github.com/connectbot/connectbot/files/2622379/dropbear_ecdsa_host_key.txt)
[dropbear_dss_host_key.txt](https://github.com/connectbot/connectbot/files/2622380/dropbear_dss_host_key.txt)

**Comment by corbinlc** [comment] 2018-11-28 00:39
The ecdsa keys are different lengths.

**Comment by corbinlc** [comment] 2018-11-28 00:47
If I simply copy the keys from kali into debian and restart the server and then try to connect via connectbot it does in fact fail.  So you can try simply swapping the keys I have provided.

Yes, just copying the different ecdsa keys back and forth will make it so you get the "proposals do not match error shows up"

That gives me a pretty easy work around (I think).  I can just have the startup script create keys of a certain size that is the same for all distros.  But ideally it would be fixed in connectbot too.

**Comment by kruton** [comment] 2018-11-28 01:51
Yes, it is a bug and will be fixed. Luckily it's simply what I surmised in https://github.com/connectbot/connectbot/issues/663#issuecomment-437523450 above.

**Comment by corbinlc** [comment] 2018-11-28 19:46
Great!  Thanks for confirm the issue and that it will be fixed.

**Comment by corbinlc** [comment] 2018-11-29 04:52
My work around works fine, so I won't harass you about this, but please to tell me when it is fixed.  I mentioned a couple of more issues that matter to UserLAnd earlier and will watch to see if they are resolved as well.

**Closed** 2020-09-04 21:25 UTC
Labels: bug
