### ISSUE TITLE
raspberrypi.local

### ISSUE THREAD

**Issue by CharlesNice** [connectbot/connectbot#671] opened 2018-11-18 20:01 UTC
I had a quick look and I didn't see anyone mention this, but I cannot connect to my little raspberry pi with: pi@raspberrypi.local 

This is the way that I normally connect on my local network, I have had no problem with desktop client (putty etc). Apparently, Iv'e been told you need the ".local", attempting to connect on pi@raspberrypi doesn't work for me. 

I can connect over the IP just fine, but my network uses DHCP, so I don't always know the IP.

Adding it as a host, it immediately says:

Connection Lost
Unable to resolve host "raspberrypi.local": No such address associated with hostname
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

Hope this helps.

-C

**Comment by Mikaela** [comment] 2018-11-25 08:01
Duplicate of https://github.com/connectbot/connectbot/issues/396

**Closed** 2018-12-17 05:55 UTC
